server:
  port: 8080
spring:
  datasource:
    hikari:
      max-lifetime: 12000
    url: jdbc:mysql://139.224.51.34:3406/exercise?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 1hblsqt!
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.onus.exercise.mapper: debug
  file:
    name: D:/logs/exercise/exercise.log